// Generated by scripts/blender/build-garage.py (bake step). Do not edit by hand.
export const GARAGE_META = {
  "room": {
    "lightmap": "lightmap.png",
    "intensity": 4.7415
  },
  "floor": {
    "lightmap": "floor_lightmap.png",
    "intensity": 3.4135,
    "size": [
      14,
      13
    ],
    "centre": [
      0,
      -1.5
    ]
  },
  "encoding": "(irradiance / intensity) ^ (1 / 2.2)",
  "tile": {
    "floor": 3,
    "wall": 4,
    "shutter": 2.4,
    "plate": 1.2
  }
} as const;
