#!/usr/bin/env node
// Render the hero studio in headless Chrome and save:
//  - public/images/poster/hero-desktop.{avif,webp}  (stage only, 16:9)
//  - public/images/poster/hero-mobile.{avif,webp}   (stage only, phone portrait @2x)
//  - public/og-image.jpg                             (whole hero incl. copy, 1200×630)
// then writes src/data/poster.ts so the page starts using the poster.
// Needs a running dev/preview server:  npm run poster -- --url http://127.0.0.1:5188/
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import puppeteer from 'puppeteer-core';
import sharp from 'sharp';

const CHROME = process.env.CHROME_PATH ?? 'C:/Program Files/Google/Chrome/Application/chrome.exe';
const urlArg = process.argv.indexOf('--url');
const base = urlArg > -1 ? process.argv[urlArg + 1] : 'http://127.0.0.1:5188/';
const OUT = 'public/images/poster';

const userDataDir = await fs.mkdtemp(path.join(os.tmpdir(), 'b188-poster-'));
const browser = await puppeteer.launch({
  executablePath: CHROME,
  headless: true,
  userDataDir,
  args: ['--no-first-run', '--ignore-gpu-blocklist', '--enable-unsafe-swiftshader'],
});

async function shoot({ width, height, scale, stageOnly }) {
  const page = await browser.newPage();
  await page.setViewport({ width, height, deviceScaleFactor: scale });
  await page.goto(`${base}?capture&nointro`, { waitUntil: 'networkidle2', timeout: 90000 });
  await page.waitForSelector('[data-studio-ready="true"]', { timeout: 60000 });
  // Let the environment map, contact shadows and reflections settle.
  await new Promise((r) => setTimeout(r, 2500));
  if (stageOnly) {
    await page.addStyleTag({ content: 'header, #top, .stage-feather { visibility: hidden !important; }' });
    await new Promise((r) => setTimeout(r, 300));
  }
  const buffer = await page.screenshot({ type: 'png' });
  await page.close();
  return buffer;
}

try {
  await fs.mkdir(OUT, { recursive: true });
  const desktop = await shoot({ width: 1600, height: 900, scale: 1.25, stageOnly: true });
  const mobile = await shoot({ width: 430, height: 932, scale: 2, stageOnly: true });
  const og = await shoot({ width: 1200, height: 630, scale: 1, stageOnly: false });

  const sizes = {};
  for (const [name, buffer] of [['hero-desktop', desktop], ['hero-mobile', mobile]]) {
    await sharp(buffer).avif({ quality: 55, effort: 5 }).toFile(`${OUT}/${name}.avif`);
    await sharp(buffer).webp({ quality: 80 }).toFile(`${OUT}/${name}.webp`);
    const meta = await sharp(buffer).metadata();
    sizes[name] = { width: meta.width, height: meta.height };
  }
  await sharp(og).jpeg({ quality: 84, mozjpeg: true }).toFile('public/og-image.jpg');

  const stamp = Date.now().toString(36);
  await fs.writeFile(
    'src/data/poster.ts',
    `// Generated by scripts/capture-poster.mjs — do not edit by hand.\n` +
      `export const POSTER = {\n` +
      `  version: '${stamp}',\n` +
      `  desktop: { src: '/images/poster/hero-desktop', width: ${sizes['hero-desktop'].width}, height: ${sizes['hero-desktop'].height} },\n` +
      `  mobile: { src: '/images/poster/hero-mobile', width: ${sizes['hero-mobile'].width}, height: ${sizes['hero-mobile'].height} },\n` +
      `} as const;\n`,
  );
  console.log('poster written', sizes);
} finally {
  await browser.close();
  await fs.rm(userDataDir, { recursive: true, force: true }).catch(() => {});
}
