// Generated by scripts/build-videos.mjs. Do not edit by hand.
// Videos per slot; a slot without an entry shows its photo.

export interface VideoClip {
  src: string;
  /** First frame, JPEG. */
  poster: string;
  width: number;
  height: number;
  /** Seconds. */
  duration: number;
}

export interface VideoSlot {
  /** 16:9, desktop and landscape. */
  wide?: VideoClip;
  /** 9:16, phones and portrait tablets. */
  tall?: VideoClip;
}

export const VIDEOS: Record<string, VideoSlot> = {
  'anatomi-2-urai': {
    wide: {
      src: '/videos/anatomi-2-urai-wide.mp4',
      poster: '/videos/anatomi-2-urai-wide.jpg',
      width: 1920,
      height: 1080,
      duration: 4
    }
  },
  'anatomi-3-rakit': {
    wide: {
      src: '/videos/anatomi-3-rakit-wide.mp4',
      poster: '/videos/anatomi-3-rakit-wide.jpg',
      width: 1920,
      height: 1080,
      duration: 4
    }
  },
  'hero-buka': {
    wide: {
      src: '/videos/hero-buka-wide.mp4',
      poster: '/videos/hero-buka-wide.jpg',
      width: 1920,
      height: 1080,
      duration: 4
    }
  }
};
