// Generated by scripts/build-videos.mjs. Do not edit by hand.
// Scroll-scrubbed videos per slot; a slot without an entry shows its photo.

export interface ScrubVideo {
  src: string;
  /** First frame, JPEG. */
  poster: string;
  width: number;
  height: number;
  /** Seconds. */
  duration: number;
}

export interface VideoSlot {
  /** 16:9, desktop and landscape. */
  wide?: ScrubVideo;
  /** 9:16, phones and portrait tablets. */
  tall?: ScrubVideo;
}

export const VIDEOS: Record<string, VideoSlot> = {
  'anatomi-bongkar': {
    wide: {
      src: '/videos/anatomi-bongkar-wide.mp4',
      poster: '/videos/anatomi-bongkar-wide.jpg',
      width: 1280,
      height: 720,
      duration: 6.5
    }
  },
  'anatomi-padam': {
    wide: {
      src: '/videos/anatomi-padam-wide.mp4',
      poster: '/videos/anatomi-padam-wide.jpg',
      width: 1280,
      height: 720,
      duration: 8
    }
  },
  'anatomi-rakit': {
    wide: {
      src: '/videos/anatomi-rakit-wide.mp4',
      poster: '/videos/anatomi-rakit-wide.jpg',
      width: 1280,
      height: 720,
      duration: 8
    }
  }
};
