// Generated by scripts/build-videos.mjs. Do not edit by hand.
// Scroll-scrubbed videos per slot; a slot without an entry shows its photo.

export interface ScrubVideo {
  src: string;
  width: number;
  height: number;
  /** Seconds. */
  duration: number;
}

export interface VideoSlot {
  /** 16:9, desktop and landscape. */
  wide?: ScrubVideo;
  /** 9:16, phones and portrait tablets. */
  tall?: ScrubVideo;
}

export const VIDEOS: Record<string, VideoSlot> = {};
